rendu/src/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'playlists#discover'
	get 'discover' => 'playlists#discover'
	get 'songs/add' => 'songs#new'
	get 'playlists/favorite' => 'playlists#favorite' # Used to add a favorite
	get 'playlists/favorites' => 'playlists#favorites' # Used to display favorites

	get ':user_id/playlists' => 'playlists#by_user'

	get 'friends' => 'friends#show'
	get 'friends/add' => 'friends#add'
	get 'friends/invite/:user_id' => 'friends#invite'
	get 'friends/accept/:user_id' => 'friends#accept'
	get 'friends/remove/:user_id' => 'friends#remove'
    
    get 'users' => 'users#show_users'
    delete 'users/:id' => 'users#destroy'
    
    delete 'playlists/:playlist_id/songs/:song_id' => 'playlists#remove_song'

	resources :playlists do
		collection do
			get :my_playlists
			get :discover
		end
	end

	resources :songs do
		collection do
			get :add
		end
	end
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	# Serve websocket cable requests in-process
	# mount ActionCable.server => '/cable'
end

rendu/src/app/models/playlist.rb
class Playlist < ApplicationRecord
    belongs_to :user

    has_many :favorites
    has_many :users, through: :favorites

    has_many :playlists_songs
    has_many :songs, through: :playlists_songs

	scope :topFavs, -> {
		select("playlists.id, playlists.*, count(favorites.id) AS favs_count").
		left_joins(:favorites).
		group("playlists.id").
		order("favs_count DESC")
	}
end

rendu/src/app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  def discover
    if user_signed_in?
      public_playlists = Playlist.where.not(user: current_user).where(public: true)
      friends_playlists = Playlist.where(user: current_user.friends).where.not(public: true)
      
      ids = []
      public_playlists.each do |id|
        ids << id
      end
      friends_playlists.each do |id|
        ids << id
      end
      
      @playlists = Playlist.topFavs.where(id: ids).limit(10)
      
      if current_user.admin
        @playlists = Playlist.where.not(user: current_user)
      end
      
    else
      @playlists = Playlist.where(public: true).topFavs.limit(10)
    end
  end

  def favorite
    if not user_signed_in?
        redirect_to new_user_session_path
    else
        if Playlist.find(params[:playlist]).users.include?(current_user)
          Playlist.find(params[:playlist]).users.delete(current_user)
        else
          Playlist.find(params[:playlist]).users << current_user
        end
        
        render 'update_fav_btn.js'
    end
  end

  def favorites
    if not user_signed_in?
        redirect_to new_user_session_path
    else
        @playlists = current_user.favs
    end
  end

  # GET /playlists
  # GET /playlists.json
  def index
    if not user_signed_in?
        redirect_to new_user_session_path
    else
        @playlists = current_user.playlists
    end
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
    if @playlist.public or (user_signed_in? and (@playlist.user == current_user or are_friends(current_user, @playlist.user) or current_user.admin))
        @isPlayer = true
    else
        redirect_to new_user_session_path
    end
  end

  # GET /playlists/new
  def new
    if not user_signed_in?
        redirect_to new_user_session_path
    else
        @playlist = Playlist.new
    end
  end

  # GET /playlists/1/edit
  def edit
  end

  def by_user
    @user = User.find(params[:user_id])
    if user_signed_in? and (current_user.admin or @user == current_user or are_friends(current_user, @user))
        @playlists = Playlist.where(user: params[:user_id])
    else
        @playlists = Playlist.where(user: params[:user_id]).where(public: true)
    end
  end

  # POST /playlists
  # POST /playlists.json
  def create
    if not user_signed_in?
        redirect_to new_user_session_path
    else
        @playlist = Playlist.new({ name: playlist_params[:name], user_id: current_user.id, public: playlist_params[:public]})

        respond_to do |format|
          if @playlist.save
            format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
            format.json { render :show, status: :created, location: @playlist }
          else
            format.html { render :new }
            format.json { render json: @playlist.errors, status: :unprocessable_entity }
          end
        end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    if not user_signed_in?
        redirect_to new_user_session_path
    else
        respond_to do |format|
          if @playlist.update(playlist_params)
            format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
            format.json { render :show, status: :ok, location: @playlist }
          else
            format.html { render :edit }
            format.json { render json: @playlist.errors, status: :unprocessable_entity }
          end
        end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    if user_signed_in? and (current_user.admin or current_user == @playlist.user)
        @playlist.destroy
        respond_to do |format|
          format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
          format.json { head :no_content }
        end
    else
        redirect_to new_user_session_path
    end
  end
  
  def remove_song
    playlist = Playlist.find(params[:playlist_id])
    if user_signed_in? and playlist.user == current_user
        playlist.songs.delete(params[:song_id])
        redirect_to playlists_url + "/" + params[:playlist_id] + "/edit"
    else
        redirect_to new_user_session_path
    end
  end
  
  def format_duration(duration)
    if duration
        text = ""
        if duration > 3600
            text += String(duration / 3600) + ":"
            duration %= 3600
        end
        if duration > 60
            text += String(duration / 60) + ":"
            duration %= 60
        end
        return text + if duration < 10 then "0" + String(duration) else String(duration) end
    end
    return duration
  end
  helper_method :format_duration

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:user_id, :name, :public)
    end
    
    def are_friends(user, other_user)
        if not user or not other_user
            return false
        end
        begin
            user.friends.find(other_user.id)
        rescue ActiveRecord::RecordNotFound => e
            return false
        end
        return true
    end
end

rendu/src/app/helpers/playlists_helper.rb
module PlaylistsHelper
end

rendu/src/app/views/playlists/_form.html.erb
<%= form_for(playlist) do |f| %>
  <% if playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br/>
    <p>Public: <%= f.check_box :public %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rendu/src/app/views/playlists/_list.html.erb
<% @playlists.each do |playlist| %>
  <h3><%= link_to playlist.name, playlist %> &mdash; <%= link_to playlist.user.username, '/' + String(playlist.user.id) + '/playlists' %> &mdash; <%= playlist.favorites.count %> &hearts;</h3>
  <ul class="no-bullet">
    <% playlist.songs.limit(3).each do |song| %>
      <li><%= song.name %></li>
    <% end %>

    <% if playlist.songs.count > 3 %>
      <li>&hellip;</li>
    <% end %>
  </ul>
  <% if current_user and current_user.admin %>
    <p><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  <% end %>
<% end %>
<% if @playlists.size() == 0 %>
<p>Nothing here...</p>
<% end %>

rendu/src/app/views/playlists/by_user.html.erb
<h2>Playlists created by <%= @user.username %></h2>

<%= render 'list', playlists: @playlists %>

rendu/src/app/views/playlists/discover.html.erb
<h2>Discover</h2>

<%= render 'list', playlists: @playlists %>

rendu/src/app/views/playlists/edit.html.erb
<h2>Editing Playlist</h2>

<%= render 'form', playlist: @playlist %>

<h3>Remove songs from this playlist</h3>
<ul>
    <% @playlist.songs.each do |song| %>
        <li><strong><%= link_to "Remove: " + song.name, playlists_path + "/" + String(@playlist.id) + "/songs/" + String(song.id), method: :delete, data: { confirm: 'Delete this song?' } %></strong></li>
    <% end %>
    <% if @playlist.songs.size() == 0 %>
        <p>This playlist is empty...</p>
    <% end %>
</ul>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

rendu/src/app/views/playlists/favorites.html.erb
<h2>Favorites</h2>

<%= render 'list', playlists: @playlists %>

rendu/src/app/views/playlists/index.html.erb
<h2>My playlists</h2>

<table>
  <% @playlists.each do |playlist| %>
    <tr>
      <td><%= link_to playlist.name, playlist %></td>
      <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
      <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Create a new playlist', new_playlist_path %>

rendu/src/app/views/playlists/new.html.erb
<h2>New Playlist</h2>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Back', playlists_path %>

rendu/src/app/views/playlists/show.html.erb
<%= link_to '♥', playlists_favorite_path(playlist: @playlist), id: "fav", class: (@playlist.users.include?(current_user) ? 'active' : ''), remote: true %>

<h2 class="playlist-name"><%= @playlist.name %></h2>

<div class="wrapper">
	<div class="player-head">
		<div id="nowPlay">
			<span id="npStatus">Paused...</span>
			<a id="npTitle" target="_blank"></a>
		</div>
		<div id="audiowrap">
			<audio preload id="audio" controls="controls">Your browser does not support HTML5 Audio!</audio>
		</div>
		<div id="buttons">
			<div id="btnPrev">&laquo;</div>
			<div id="btnNext">&raquo;</div>
		</div>
	</div>
	<div id="plwrap">
		<ul id="plList" class="no-bullet">
			<% @playlist.songs.each do |song| %>
				<li data-filename="<%= song.filename %>" data-name="<%= song.name %>" data-url="<%= song.original_url %>" data-id="<%= song.id %>">
					<div class="plItem">
						<div class="plNum"></div>
						<div class="plLength"><%= format_duration(song.duration) %></div>
						<div class="plTitle"><%= song.name %></div>
					</div>
				</li>
			<% end %>
		</ul>
	</div>
</div>

<script>initPlayer()</script>

<!--
<%= link_to 'Add a song', add_songs_path() %> |
<% if current_user and @playlist.user.id == current_user.id %>
	<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<% end %>
-->