rendu/src/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'playlists#discover'
	get 'discover' => 'playlists#discover'
	get 'songs/add' => 'songs#new'
	get 'playlists/favorite' => 'playlists#favorite' # Used to add a favorite
	get 'playlists/favorites' => 'playlists#favorites' # Used to display favorites

	get ':user_id/playlists' => 'playlists#by_user'

	get 'friends' => 'friends#show'
	get 'friends/add' => 'friends#add'
	get 'friends/invite/:user_id' => 'friends#invite'
	get 'friends/accept/:user_id' => 'friends#accept'
	get 'friends/remove/:user_id' => 'friends#remove'
    
    get 'users' => 'users#show_users'
    delete 'users/:id' => 'users#destroy'
    
    delete 'playlists/:playlist_id/songs/:song_id' => 'playlists#remove_song'

	resources :playlists do
		collection do
			get :my_playlists
			get :discover
		end
	end

	resources :songs do
		collection do
			get :add
		end
	end
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	# Serve websocket cable requests in-process
	# mount ActionCable.server => '/cable'
end

rendu/src/app/models/song.rb
class Song < ApplicationRecord
    has_many :playlists_songs
    has_many :playlists, through: :playlists_songs
end

rendu/src/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    if not user_signed_in?
        redirect_to new_user_session_path
    else
        @song = Song.new
    end
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    if not user_signed_in?
        redirect_to new_user_session_path
    else
      if Song.where(original_url: song_params[:original_url]).exists?
        @song = Song.where(original_url: song_params[:original_url]).first
        @song.playlists << Playlist.where(id: song_params[:playlist_ids])

        respond_to do |format|
          format.html { redirect_to playlists_path, notice: 'Song was successfully created.' }
          format.json { render :show, status: :created, location: @song }
        end
      else
        data = ""
        cmd = "youtube-dl -J " + song_params[:original_url] + " 2>> /dev/null"
        IO.popen(cmd) { |f| data = f.gets }
        metadata = JSON.parse(data)

        filename = `date +%s%N | tr -d "\n"`

        value = system("youtube-dl", song_params[:original_url], "-x", "--audio-format", "mp3", "-o", Dir.pwd + "/public/downloads/" + filename + ".%(ext)s")

        @song = Song.new({ filename: filename, name: metadata["title"], duration: metadata["duration"], original_url: song_params[:original_url] })

        @song.playlists << Playlist.where(id: song_params[:playlist_ids])

        respond_to do |format|
          if @song.save and value
            format.html { redirect_to playlists_path, notice: 'Song was successfully created.' }
            format.json { render :show, status: :created, location: @song }
          else
            format.html { render :new }
            format.json { render json: @song.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    if not user_signed_in?
        redirect_to new_user_session_path
    else
        respond_to do |format|
          if @song.update(song_params)
            format.html { redirect_to @song, notice: 'Song was successfully updated.' }
            format.json { render :show, status: :ok, location: @song }
          else
            format.html { render :edit }
            format.json { render json: @song.errors, status: :unprocessable_entity }
          end
        end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    if not user_signed_in?
        redirect_to new_user_session_path
    else
        @song.destroy
        respond_to do |format|
          format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
          format.json { head :no_content }
        end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :filename, :original_url, :playlist_ids => [])
    end
end

rendu/src/app/helpers/songs_helper.rb
module SongsHelper
end

rendu/src/app/views/songs/_form.html.erb
<%= form_for(song) do |f| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :original_url, placeholder: "URL from YouTube/Soundcloud/etc." %>
  </div>

  <canvas id="spinner" width="500"></canvas>

  <div class="field song-checkboxes">
    <%=collection_check_boxes(:song, :playlist_ids, current_user.playlists, :id, :name)%>
  </div>

  <div class="actions">
    <%= f.submit "Add" %>
  </div>
<% end %>

rendu/src/app/views/songs/edit.html.erb
<h2>Editing Song</h2>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

rendu/src/app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Songs</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Filename</th>
      <th>Original url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.name %></td>
        <td><%= song.filename %></td>
        <td><%= song.original_url %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

rendu/src/app/views/songs/new.html.erb
<h2>Add a Song</h2>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

rendu/src/app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Filename:</strong>
  <%= @song.filename %>
</p>

<p>
  <strong>Original url:</strong>
  <%= @song.original_url %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>