rendu/src/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'playlists#discover'
	get 'discover' => 'playlists#discover'
	get 'songs/add' => 'songs#new'
	get 'playlists/favorite' => 'playlists#favorite' # Used to add a favorite
	get 'playlists/favorites' => 'playlists#favorites' # Used to display favorites

	get ':user_id/playlists' => 'playlists#by_user'

	get 'friends' => 'friends#show'
	get 'friends/add' => 'friends#add'
	get 'friends/invite/:user_id' => 'friends#invite'
	get 'friends/accept/:user_id' => 'friends#accept'
	get 'friends/remove/:user_id' => 'friends#remove'
    
    get 'users' => 'users#show_users'
    delete 'users/:id' => 'users#destroy'
    
    delete 'playlists/:playlist_id/songs/:song_id' => 'playlists#remove_song'

	resources :playlists do
		collection do
			get :my_playlists
			get :discover
		end
	end

	resources :songs do
		collection do
			get :add
		end
	end
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	# Serve websocket cable requests in-process
	# mount ActionCable.server => '/cable'
end

rendu/src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlylstIt</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <nav>
      <div class="link-left"><%= link_to('Discover', discover_playlists_path) %></div>

      <% if user_signed_in? %>
        <div class="link-left"><a href="/friends">Friends</a></div>
        <div class="link-left"><%= link_to('Favorites', playlists_favorites_path) %></div>

        <div class="link-right"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></div>
        <% if user_signed_in? and current_user.admin %>
            <div class="link-right"><%= link_to('Manage users', users_path) %></div>
        <% end %>
        <div class="link-right"><%= link_to('Edit Account', edit_user_registration_path) %></div>
        <div class="link-right"><%= link_to('My Playlists', playlists_path) %></div>
        <div class="link-right"><%= link_to('Add Song', add_songs_path) %></div>
      <% else %>
        <div class="link-right"><%= link_to('Login', new_user_session_path) %></div>
        <div class="link-right"><%= link_to('Register', new_user_registration_path) %></div>
      <% end %>
    </nav>
    <% if @isPlayer %>
      <div id="player-container">
        <h1>plylst.it</h1>
        <%= yield %>
      </div>
    <% else %>
      <div id="container">
        <h1>plylst.it</h1>
        <%= yield %>
      </div>
    <% end %>
  </body>
</html>